# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vstueckz', models.PositiveSmallIntegerField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bestellartikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('datum', models.DateTimeField()),
                ('bewertung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lieferbarkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mwst', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.AddField(
            model_name='bestellung',
            name='lieferadresse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lads', to='shop.Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestellung',
            name='rechnungsadresse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rads', to='shop.Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestellung',
            name='status',
            field=models.CharField(choices=[('b', 'bestellt'), ('v', 'versendet'), ('s', 'storniert')], default='bestellt', max_length=255),
        ),
        migrations.AddField(
            model_name='kunde',
            name='passwort',
            field=models.CharField(default='passwort', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='datum',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Bluray',
            fields=[
                ('artikel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Artikel')),
                ('regisseur', models.CharField(max_length=255)),
                ('jahr', models.PositiveSmallIntegerField()),
                ('genre', models.CharField(max_length=255)),
                ('dauer', models.IntegerField()),
            ],
            bases=('shop.artikel',),
        ),
        migrations.CreateModel(
            name='Buch',
            fields=[
                ('artikel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Artikel')),
                ('autor', models.CharField(max_length=255)),
                ('verlag', models.CharField(max_length=255)),
                ('seiten', models.PositiveSmallIntegerField()),
                ('isbn', models.CharField(max_length=255)),
            ],
            bases=('shop.artikel',),
        ),
        migrations.CreateModel(
            name='SonstigerArtikel',
            fields=[
                ('artikel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Artikel')),
            ],
            bases=('shop.artikel',),
        ),
        migrations.AddField(
            model_name='lieferbarkeit',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Artikel'),
        ),
        migrations.AddField(
            model_name='lieferbarkeit',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Land'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Artikel'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Kunde'),
        ),
        migrations.AddField(
            model_name='bestellartikel',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Artikel'),
        ),
        migrations.AddField(
            model_name='bestellartikel',
            name='bestellung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Bestellung'),
        ),
        migrations.AddField(
            model_name='bestellung',
            name='artikel',
            field=models.ManyToManyField(to='shop.Artikel'),
        ),
    ]
